### ISSUE TITLE
Errors are not closed after closing file

### ISSUE THREAD

**Issue by kanlukasz** [ctf0/vscode-htmlhint#1]
Hello,
The old extension is not updated and nobody fixes any errors there so it's really great to see a new fork 👍

Ok, now let's go to the point - you have one same little bug in your fork.
- After closing the file with errors, these errors still appear in the "PROBLEMS" section

I think that after closing the file the errors should disappear from `PROBLEMS`

Right now the errors disappear only after reloading VsCode

From original repo: https://github.com/microsoft/vscode-htmlhint/issues/60

**Comment by ctf0** [comment]
np, i will look into it, thanx for reporting it

**Comment by ctf0** [comment]
after trying for 3 hrs & following https://code.visualstudio.com/api/language-extensions/c-extension-guide sadly i cant get it to work as expected, so any one can help is appreciated.

**Comment by kanlukasz** [comment]
OK, thank you for your effort
I can't help you with this because I'm just a PHP junior dev
I hope someone else will help
