### ISSUE TITLE
Extension Status

### ISSUE THREAD

**Issue by coliff** [ctf0/vscode-htmlhint#4]
Hello! I'm a maintainer of the official HTMLHint extension. What is the status of this extension now?

If it is no longer maintained you could consider marking it as deprecated and point users to the official extension:
https://marketplace.visualstudio.com/items?itemName=HTMLHint.vscode-htmlhint

If you'd like to keep it as it is, that's completely fine of course - just wanted to let you know that the official extension is live and will continue to receive updates. :-)

**Comment by ctf0** [comment]
yeah sure will do, thanks for the headsup

**Comment by ctf0** [comment]
https://github.com/microsoft/vscode-discussions/discussions/1#discussioncomment-3919994
